---
dependency:
  name: galaxy
  options:
    ignore_certs: True
driver:
  name: docker
platforms:
  - name: instance
    image: dokken/centos-8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible